// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCdlwxLWkzhkYOy24WtSMm_U9yQJHwoqI',
    appId: '1:236012585414:web:51bd43faa1a8aa1bc072c7',
    messagingSenderId: '236012585414',
    projectId: 'tiktok-clone-2bae6',
    authDomain: 'tiktok-clone-2bae6.firebaseapp.com',
    storageBucket: 'tiktok-clone-2bae6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3BYx6hb7CMHeWTS-0zEsHPnUYpSDoeKc',
    appId: '1:236012585414:android:266ad42fab0ac5b0c072c7',
    messagingSenderId: '236012585414',
    projectId: 'tiktok-clone-2bae6',
    storageBucket: 'tiktok-clone-2bae6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3yN5TVBLBl6vCjggOYTOpEapEBDUfX8s',
    appId: '1:236012585414:ios:10ff6c08cc049da8c072c7',
    messagingSenderId: '236012585414',
    projectId: 'tiktok-clone-2bae6',
    storageBucket: 'tiktok-clone-2bae6.appspot.com',
    iosBundleId: 'com.example.tiktokClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3yN5TVBLBl6vCjggOYTOpEapEBDUfX8s',
    appId: '1:236012585414:ios:dd8c15ec10e7a3b2c072c7',
    messagingSenderId: '236012585414',
    projectId: 'tiktok-clone-2bae6',
    storageBucket: 'tiktok-clone-2bae6.appspot.com',
    iosBundleId: 'com.example.tiktokClone.RunnerTests',
  );
}
